MV3 Extension boilerplate
ipfs/ipfs-companion pull request #1044
Opened 2022-01-13 19:24 UTC by meandavejustice

This is the starting point for Manifest v3 extension.

What currently works?
* simple redirects from `ipfs.io` and `dweb` links.
* dnslink urls are fetched and added to the DeclarativeNetRequest api ruleset for redirection.
* added workflow to start testing out CI
* add typescript
* add prettier
* add eslint
* building with esbuild for ⚡ fast builds
* adds boilerplate for popup

All of this is in `/mv3`

cc/ @lidel

2022-01-25 19:03 UTC, lidel requested changes
Thanks!  Small asks before we merge (inline)

2022-01-25 19:03 UTC, lidel commented on mv3/package.json
> +    ],
No need to support everything, let's narrow this down to runtimes where people use Companion:

```suggestion
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "Firefox ESR"
    ],
```

2022-01-25 19:03 UTC, lidel commented on mv3/package.json
> +      "last 1 safari version"
Will add Safari when they support all the APIs we need, so far I don't believe it's the case. 
```suggestion
      "last 1 chrome version",
      "last 1 firefox version"
```

2022-01-25 19:03 UTC, lidel commented on mv3/addon/background.ts
> +  // @ts-ignore
`@ts-ignore` like this triggers github action check which prints same warning 3 times below (can we remove this noise?)

2022-01-26 16:22 UTC, meandavejustice commented
@lidel Comments addressed 👍

2022-02-07 23:14 UTC, meandavejustice commented
@lidel Could I get yours 👀 on this again? Thanks!

2022-03-28 13:27 UTC, lidel requested changes
Thank you @meandavejustice, and apologies for late review.

Dynamic rules are pretty powerful, and I think we should be able to live with them as long we add proper cache around their creation. 


Left some feedback below:
- :warning: important things we should fix
  - lmk if you prefer to do them in this PR or merge as-is and  track them in separate issues
- :thought_balloon: lower priority thoughts on style and nice-to-haves

2022-03-28 13:27 UTC, lidel commented on mv3/addon/rules.json
> +        "transform": { "scheme": "http", "host": "localhost", "port": "8080" }
:thought_balloon: given that port will be something that can be changed by the user, we will most likely end up adding these as dynamic rules during startup.

2022-03-28 13:27 UTC, lidel commented on .github/workflows/ci-mv3.yml
> +          key: ${{ runner.os }}-${{ hashFiles('package*json', 'yarn.lock') }}
:warning: please  remove `yarn.lock` and this cache – `npm ci` uses `package-lock.json` and ignores `yarn.lock` anyway (which is  good, we want to try using `package-lock.json` and remove `yarn` dependency)

2022-03-28 19:52 UTC, meandavejustice commented on mv3/addon/background.ts
> +  const id = Math.floor(Math.random() * 29999);
I could not find an answer for this in `declarativeNetRequest` docs. There is a possibility that they are namespaced or scoped to the `id` declared under `rule_resources` key in the manifest.json. But just to be safe I'm going to add a prefix to the id of the extension name :)

2022-03-28 19:58 UTC, meandavejustice commented on mv3/addon/background.ts
> +  const contentPath = await client.resolve(`/ipns/${domain}`);
I realized this is an out of date file. I will push the updates shortly with the updated branch I've been working in 🤦. Luckily for me there was some things you caught that I wasn't doing in the new branch! so it was NOT a wasted effort :)

2022-03-29 00:35 UTC, meandavejustice commented
@lidel Thanks again for the review, I apologize for the branching mixup. I've got it working now correctly in this branch and addressed most of your comments. (I have two of them added to my todo list for the week). I'm going to go ahead and close this pr and open up a fresh one later on in the week. I need to add an updated list of features, and screenshots and clean up the git history.

2022-03-29 00:35 UTC, closed without merging