[WIP] feat: add telemetry to companion
ipfs/ipfs-companion pull request #1117
Opened 2022-12-16 20:35 UTC by SgtPooki

- feat: add types for state
- tmp

2022-12-17 03:05 UTC, SgtPooki commented
@juliaxbow I would love your opinion on the formatting of the telemetry section

2022-12-17 04:12 UTC, juliaxbow commented
**Descriptions**
- **Telemetry section** In the description, would say "To assist in our efforts, please consent to the collection of these metrics by toggling "on" in the corresponding section. You can change this setting at any time by navigating back to the Companion Preferences page."  It's a little unusual to offer consent via a toggle but I think it's ok?
- Is the toggle default to on? If so, we should change the wording even further. Something like "IPFS Companion is collecting minimal telemetry data to improve and prioritize our work. You may opt out of the collection of these metrics by toggling "off" in the corresponding section below. You can change this setting ......"
- **Metrics Section** the metric collection description, I would change wording to "Sends ‘session’ and ‘view’ events only when ipfs-companion is enabled and your browser is not idle." Current wording raises the question of who is sending this information where? 
- The section header "minimal metrics: ..." makes it seem like there are additional, more intrusive metrics somewhere. Until we have other metrics we're tracking I think we can just call it "Session & Companion views." The Telemetry description already points to the fact that these are minimal. 

**Other**
- "Read More" links on the page have a link-out icon, so would add that in. (in the screenshot below i have the same link blue because I think all link-out icons should look like links but keep consistent with the rest of the page for now ;) )
- The toggle is centered but it doesn't look like it is. Until we have more sections & metrics that we're tracking, I would move it up to be top-aligned with the first sentence in the description. I know this is inconsistent with all other toggles on the page but to me it's more clear what the user is agreeing to. This is subjective, though, so feel free to ignore.

Incl screenshot to show the _suggested_ toggle alignment
<img width="576" alt="Screen Shot 2022-12-16 at 8 07 57 PM" src="https://user-images.githubusercontent.com/58958327/208224144-cadbd0df-3b1d-40ef-853b-bf00c45e8abf.png">

2023-01-11 00:22 UTC, lidel requested changes
Looks sensible, as long we address below:
1. We should not be sending requests to Countly every minute a user uses a browser. 
   (I assume that is what is happening? I was unable to build this and test locally)
   - This causes many issues, for example drains laptop battery by waking up WIFI when no internet conneciton would be needed otherwise. 
   - As discussed, figure a way to batch things so we report them only once an hour or once a day.  
1. Regular people don't know hat 'session' and 'view' means. 
   - See my suggestions below on humanizing the language :)

2023-01-11 00:22 UTC, lidel commented on add-on/_locales/en/messages.json
> +    "message": "A `session` event - every 60 seconds.",
Would this be better?
```suggestion
    "message": "A `session` event  for every minute the extension was active.",
```

2023-01-11 00:22 UTC, lidel commented on add-on/_locales/en/messages.json
> +    "message": "A `view` event - only for ipfs-companion pages.",
Users have no idea browser extensions are regular webpages behind the scenes.
Maybe more explicit:

```suggestion
    "message": "A `view` event for every time a part of extension's user interface is visible.",
```

2023-01-11 00:22 UTC, lidel commented on add-on/src/lib/options.js
> +  telemetryGroupTracking: false
- rename `telemetryGroupMinimal` to `telemetryFeatures`
- remove `telemetryGroupMarketing` and `telemetryGroupTracking` (we are not doing these, afaik don't plan to do it, so no reason to trigger anyone with this language)

2023-01-11 00:22 UTC, lidel commented on add-on/src/lib/telemetry.js
> +  console.log('checkConsent(\'tracking\'): ', getMetricsProviderInstance().checkConsent('tracking'))
Remove all `console.log` calls, use scoped `debug` logger instead – see `src/lib/on-installed.js`, we want something similar:

```js
import debug from 'debug'
const log = debug('ipfs-companion:telemetry')
log(`checkConsent(foo): ${bar}`)
```
```

2023-01-13 06:10 UTC, SgtPooki reviewed
Self review

2023-01-13 06:10 UTC, SgtPooki commented on add-on/src/lib/notifier.js
> +          message
Lint fixes

2023-01-13 06:10 UTC, SgtPooki commented on add-on/src/lib/options.js
> +import { isIPv4, isIPv6 } from 'is-ip'
Vscode ordered imports on save. Willing to remove

2023-01-13 06:10 UTC, SgtPooki commented on add-on/src/options/page.js
> +  })}
@SgtPooki to update

2023-01-13 06:10 UTC, SgtPooki commented on add-on/src/types.d.ts
> +
Typescript types supported for linting. No work done for building validation (except from linter) nor exporting types (shouldn't be needed).

Errors show in vscode but don’t fail build yet

2023-01-13 06:10 UTC, SgtPooki commented on docs/telemetry/COLLECTED_DATA.md
> +# Collected telemetry data
@whizzzkid @lidel first demo of what COLLECTED_DATA.md should look like as defined from ipfs-shipyard/ignite-metrics#35.  Lmk what you think

2023-01-13 06:19 UTC, SgtPooki commented
> We should not be sending requests to Countly every minute a user uses a browser.
> (I assume that is what is happening? I was unable to build this and test locally)

I just tested again, and since the “autoTrack” is set to false, countly does not send session_duration events anymore (those are sent by countly if you call `.track_sessions()`). See my comment about state.active and starting/ending sessions.

Also, i feel like we should so some implementation of observability on “idle” state. Any thoughts on changing the current use of “runOfNotIdle” to a boolean on the state object?  We could have a single interval that checks browser.idle.queryState and updates state.isIdle. Then check that variable prior to actions.

We could also add “runIfNotIdle” as a function to the state object so it’s re-usable. 

The main thing i want to stay away from is a pattern of multiple intervals scattered throughout the codebase, so lmk if you two have any thoughts here please!

2023-01-18 04:10 UTC, SgtPooki commented
@lidel @whizzzkid note that I pushed up a fix for the CI failures using the version of ignite-metrics at https://github.com/ipfs-shipyard/ignite-metrics/pull/60. will update package.json once I can use the version on npm again.

2023-01-27 18:09 UTC, SgtPooki commented
FYI @lidel @whizzzkid I had some changes locally that weren't pushed up... getting those up now

2023-01-27 21:02 UTC, SgtPooki commented
Agreed with @whizzzkid. Metrics are only sent (currently) when interacting with the extension (enabling/disabling, viewing different pages), so battery use should not be a concern.

2023-01-27 21:03 UTC, merged